controller_server:
  ros__parameters:
    use_sim_time: true
    enable_stamped_cmd_vel: true
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.3

      lookahead_dist: 0.6
      min_lookahead_dist: 0.4
      max_lookahead_dist: 1.0
      lookahead_time: 2.0
      
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.196
      rotate_to_heading_angular_vel: 0.8
      
      allow_reversing: false
      use_velocity_scaled_lookahead_dist: true

      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.1
      
      transform_tolerance: 0.2
