teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear: 
      x: 0.44   # 50% of max speed   
    scale_linear_turbo:
      x: 0.88  # 100% of max speed  

    axis_angular:   # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.6  # 50% of max speed
    scale_angular_turbo:
      yaw: 1.2  # 100% of max speed

    enable_button: 5  # Left trigger button
    enable_turbo_button: 4  # Right trigger button
