twist_mux:
  ros__parameters:
    topics:
      gamepad:
        topic   : cmd_vel_gamepad_stamped
        timeout : 0.5
        priority: 100  # Highest priority
      navigation:
        topic   : cmd_vel_nav_stamped # cmd_vel_nav_stamped cmd_vel_nav_safe SWTICH when not using collision monitor
        timeout : 1.0
        priority: 10   # Lower priority
    
    use_stamped: true