slam_toolbox:
  ros__parameters:
    use_sim_time: true

    mode: 'mapping'
    slam_param_version: 2

    provide_odom_frame: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_frame: base_link

    scan_topic: /scan
    odom_topic: /diff_drive_base_controller/odom

    use_scan_matching: true
    use_scan_barycenter: true

    publish_pose: true
    publish_pose_rate: 20.0

    use_loop_closure: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5

    map_update_interval: 2.0
