controller_server:
  ros__parameters:
    use_sim_time: true
    enable_stamped_cmd_vel: true
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      # Linear
      desired_linear_vel: 0.30
      min_linear_vel: 0.10
      max_linear_accel: 0.6
      max_linear_decel: 0.8

      # Angular
      rotate_to_heading_angular_vel: 0.9
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.8

      # Lookahead
      lookahead_dist: 0.55
      min_lookahead_dist: 0.40
      max_lookahead_dist: 0.90
      lookahead_time: 1.0
      use_velocity_scaled_lookahead_dist: true

      # Curvature regulation
      curvature_lookahead_dist: 0.6
      regulated_linear_scaling_min_radius: 0.8
      regulated_linear_scaling_min_speed: 0.15

      transform_tolerance: 0.1